"""Per-class spell allotment derived from the SRD 5.2.1 progression tables.

The structured progression catalog lives at
``assets/srd5_2/progression.json`` and is generated by
``tools/parse_srd_progression.py``.  This module exposes a small typed
API the character wizard / level-up flow uses to compute a
character's spellcasting block from their *class* and *level* — the
single source of truth replaces the previously hard-coded level-1
dictionaries on each :class:`Archetype`.

Public entry points
-------------------

``progression_for(class_key, level)``
    Raw progression record for the given class/level (or ``None``).

``spellcasting_block(class_key, level)``
    Returns the dict shape consumed by ``character_spells`` /
    ``CombatantState`` (``ability``, ``cantrips_known``, ``spells_known``,
    ``slots`` keyed by spell-level string).  Returns ``None`` for
    non-casters or unknown classes.

``casting_style_for(class_key)``
    ``"known" | "prepared" | None``.

``slots_dict(class_key, level)``
    Just the ``{"1": n, "2": n, ...}`` slot map (only non-zero entries).

The SRD calls the Warlock's slots *Pact Magic* and they are all the
same level; we expand them into the same ``{slot_level: count}`` shape
so downstream slot-accounting code does not need a special case.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parents[3]
_PROGRESSION_PATH = _REPO_ROOT / "assets" / "srd5_2" / "progression.json"

# Convenience: aliases mapping wizard archetype keys → SRD class keys.
# The wizard uses flavour names (witch / scholar / ...) so consumers can
# resolve via either key without leaking the SRD vocabulary.
ARCHETYPE_TO_CLASS: dict[str, str] = {
    "witch": "warlock",
    "scholar": "wizard",
    # Direct passthroughs keep the function callable with raw class keys.
    "bard": "bard",
    "cleric": "cleric",
    "druid": "druid",
    "paladin": "paladin",
    "ranger": "ranger",
    "sorcerer": "sorcerer",
    "warlock": "warlock",
    "wizard": "wizard",
}

# Min/max level bounds — SRD progression covers 1..20.
MIN_LEVEL = 1
MAX_LEVEL = 20


@lru_cache(maxsize=1)
def _load() -> dict[str, Any]:
    if not _PROGRESSION_PATH.exists():
        return {"classes": {}}
    with _PROGRESSION_PATH.open(encoding="utf-8") as fh:
        return json.load(fh)


def _resolve_class_key(class_or_archetype: str) -> str | None:
    if not class_or_archetype:
        return None
    key = class_or_archetype.strip().lower()
    return ARCHETYPE_TO_CLASS.get(key, key if key in _load().get("classes", {}) else None)


def class_record(class_or_archetype: str) -> dict[str, Any] | None:
    """Top-level record for a class (ability, casting_style, kind, progression)."""
    key = _resolve_class_key(class_or_archetype)
    if key is None:
        return None
    return _load().get("classes", {}).get(key)


def casting_style_for(class_or_archetype: str) -> str | None:
    rec = class_record(class_or_archetype)
    return rec.get("casting_style") if rec else None


def progression_for(class_or_archetype: str, level: int) -> dict[str, Any] | None:
    """Return the level-bucket for ``class_or_archetype`` at ``level``.

    Levels outside ``1..20`` are clamped to the nearest valid bucket.
    """
    rec = class_record(class_or_archetype)
    if rec is None:
        return None
    clamped = max(MIN_LEVEL, min(MAX_LEVEL, int(level)))
    return rec.get("progression", {}).get(str(clamped))


def slots_dict(class_or_archetype: str, level: int) -> dict[str, int]:
    """Return a ``{spell_level_str: count}`` map of *non-zero* slots.

    Warlock pact slots collapse into a single entry whose key is the
    pact-slot level (e.g. ``{"3": 2}`` at warlock 5).  Half-casters
    naturally produce keys ``"1".."5"`` only; full casters ``"1".."9"``.
    """
    rec = class_record(class_or_archetype)
    bucket = progression_for(class_or_archetype, level)
    if rec is None or bucket is None:
        return {}
    if rec.get("kind") == "warlock":
        pact = bucket.get("pact_slots") or {}
        count = int(pact.get("count", 0))
        slot_level = int(pact.get("level", 0))
        if count <= 0 or slot_level <= 0:
            return {}
        return {str(slot_level): count}
    out: dict[str, int] = {}
    for idx, n in enumerate(bucket.get("slots", []) or [], start=1):
        if int(n) > 0:
            out[str(idx)] = int(n)
    return out


def spellcasting_block(class_or_archetype: str, level: int) -> dict[str, Any] | None:
    """Build the ``spellcasting`` dict consumed by the character wizard.

    Returns ``None`` for non-casters / unknown classes so callers can
    treat a missing block as "no spells".
    """
    rec = class_record(class_or_archetype)
    bucket = progression_for(class_or_archetype, level)
    if rec is None or bucket is None:
        return None
    block: dict[str, Any] = {
        "ability": rec.get("ability"),
        "cantrips_known": int(bucket.get("cantrips_known", 0)),
        "spells_known": int(bucket.get("spells_known", 0)),
        "slots": slots_dict(class_or_archetype, level),
        "casting_style": rec.get("casting_style"),
        "kind": rec.get("kind"),
    }
    if rec.get("kind") == "warlock":
        # Surface the pact-slot detail (spell-level all slots cast at)
        # for callers that want to show "Pact Magic: 2 × level-3 slots"
        # without re-deriving it from the slot map.
        pact = bucket.get("pact_slots") or {}
        block["pact_slots"] = {
            "count": int(pact.get("count", 0)),
            "level": int(pact.get("level", 0)),
        }
        if "invocations" in bucket:
            block["invocations"] = int(bucket["invocations"])
    return block


def proficiency_bonus_for(class_or_archetype: str, level: int) -> int:
    """SRD proficiency bonus for the given class+level (defaults to ``2``)."""
    bucket = progression_for(class_or_archetype, level)
    if bucket is None:
        # Standard table: +2 at 1-4, +3 at 5-8, +4 at 9-12, +5 at 13-16, +6 at 17-20.
        clamped = max(MIN_LEVEL, min(MAX_LEVEL, int(level)))
        return 2 + (clamped - 1) // 4
    return int(bucket.get("proficiency_bonus", 2))


__all__ = [
    "ARCHETYPE_TO_CLASS",
    "MAX_LEVEL",
    "MIN_LEVEL",
    "casting_style_for",
    "class_record",
    "progression_for",
    "proficiency_bonus_for",
    "slots_dict",
    "spellcasting_block",
]

